### ISSUE TITLE
addTab within js

### ISSUE THREAD

**Issue by cherimo** [viewweiwu/vue3-tabs-chrome#17]
Hi, how can I add tab within JS?
I can't call addTab without importing it first right?

```
<script setup>
import Vue3TabsChrome from 'vue3-tabs-chrome'
import 'vue3-tabs-chrome/dist/vue3-tabs-chrome.css'
import { defineComponent, reactive, ref } from 'vue'

const tabs = reactive([
        {
          label: 'Dashboard',
          key: 'dashboard',
          dragable: false,
          swappable: false,
          closable: false,
        },
])

const tab = ref('dashboard')

</script>
```

**Comment by viewweiwu** [comment]
https://viewweiwu.github.io/vue3-tabs-chrome/
Here are some examples of use.
```js
const handleAdd = () => {
  const key = 'tab' + Date.now()
  tabRef.value.addTab({
    label: 'New Tab',
    key
  })
  tab.value = key
}
```

**Comment by cherimo** [comment]
> https://viewweiwu.github.io/vue3-tabs-chrome/ Here are some examples of use.
> 
> ```js
> const handleAdd = () => {
>   const key = 'tab' + Date.now()
>   tabRef.value.addTab({
>     label: 'New Tab',
>     key
>   })
>   tab.value = key
> }
> ```

Thanks it worked
