### ISSUE TITLE
is-mousedown-active 属性无效

### ISSUE THREAD

**Issue by xinheHuang** [viewweiwu/vue3-tabs-chrome#7]
https://github.com/viewweiwu/vue3-tabs-chrome/blob/2b2a4062990dba9daaf0255b2758b4c9db38000c/package/vue3-tabs-chrome.vue#L177-L178
下面那行代码是不是应该删掉？

**Comment by viewweiwu** [comment]
可能是有问题的，让我检查下

**Comment by viewweiwu** [comment]
如你所说确实是有问题的，目前已经修复。可安装 0.3.1 版本
