### ISSUE TITLE
how to add new tabs to end of tabs?

### ISSUE THREAD

**Issue by lokize** [viewweiwu/vue3-tabs-chrome#9]
Hi, i cant add new tabs, i not using typescript in my project and when i try adding new tabs not work, how to make that?

Thanks!

**Comment by viewweiwu** [comment]
<img width="1626" alt="image" src="https://user-images.githubusercontent.com/14287892/169023708-d6a8cfd4-0cd6-47bc-beb8-7b9c6e4dece5.png">
https://codesandbox.io/s/crazy-mcclintock-p514v?file=/src/App.vue:1035-1112

**Comment by lokize** [comment]
working, thanks for help!
